### PR TITLE
fix: drop required node to <=14.0.0

### PR DESCRIPTION
**Pull request by srl295**
subset of 4f25898497c9b6e8c25d88f386a5262e702d9617 from #3 

Fixes: #2

Co-authored-by: Jordan Harband @ljharb

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
what about running the tests on node 12? we may as well reopen #3 ;-)

**Comment by srl295** [comment]
> what about running the tests on node 12? we may as well reopen #3 ;-)

this says node 12 is ALL GOOD at the moment.

**Comment by RafaelGSS** [comment]
The tests will be included at #5

**Review by RafaelGSS — APPROVED** [review]
Thank you!

**Pull request merged**
