### PR TITLE
Switch to TypeScript. Normalized output font size

### PR DESCRIPTION
**Pull request by mirasayon**
Hi everyone. I like this package (except the giant output message), it helps me a lot.

I would like to contribute to the development of this project. 
I'm new to package development, so feel free to give feedback.

Here are the main changes:
1. Switched to TypeScript and added types.
2. Normalized output message font size and added styles to it.
3. Chore: Updated all dependencies.
4. Switched formatter from `standard` to `biome`.

### CODE REVIEW

**Review by RafaelGSS — CHANGES_REQUESTED** [review]
Hi, thanks for the PR!

However,  I don't see this package using Typescript for any reason. Also, if you don't like the ASCII danger/all good message I suggest opening a PR to introduce a new flag to this cli (something like --plain-text) that will output the message as raw "Danger" instead of the ASCII one.

**Comment by mirasayon** [comment]
> Hi, thanks for the PR!
> 
> However, I don't see this package using Typescript for any reason. Also, if you don't like the ASCII danger/all good message I suggest opening a PR to introduce a new flag to this cli (something like --plain-text) that will output the message as raw "Danger" instead of the ASCII one.

I agree about the flags in the CLI. But I wanted to add TypeScript to make the code easier to maintain. And in order to be able to further develop this package, I need Typescript.

**Comment by RafaelGSS** [comment]
Sorry, I then suggest you fork the repository and release it under your name: @mirasayon/is-my-node-vulnerable

**Comment by mirasayon** [comment]
> Sorry, I then suggest you fork the repository and release it under your name: @mirasayon/is-my-node-vulnerable

as you wish

**Pull request closed without merging**
