### PR TITLE
Break source code into modules

### PR DESCRIPTION
**Pull request by trivikr**
This PR attempts to breaks source code into modules.

While breaking the source code, I merged the duplicate code in `eol-versions` and `isNodeEOL`.
I also checked in the contents of content and etag files for schedule and security. This will reduce `GET` calls when etag is latest and is verified using `HEAD` calls. We can also set up recurring GitHub workflow to update the contents of cache.

This will also allow migrating to TypeScript in future, and either transpiling or type stripping using [amaro](https://www.npmjs.com/package/amaro) depending on what maintainers think. It will also allow adding unit tests using Node.js Test Runner for individual components.

### CODE REVIEW

**Review by RafaelGSS — COMMENTED** [review]
What's the reasoning behind this change? 

To be honest, I don't see this package adopting TypeScript for any reason (as I said in https://github.com/RafaelGSS/is-my-node-vulnerable/pull/24)

If the idea was to make the core clearer, that's reasonable. Although, I feel this is a bit of overengineering for a quite simple project.

**Comment by trivikr** [comment]
> What's the reasoning behind this change?

Ease of maintenance, like ability to add unit tests. Only the files being edited will be changed in future PRs.
I've given examples on how this reduced duplicate code by creating `isNodeEOL`, and reduced `GET` calls by vendoring etag and JSON files.

> I don't see this package adopting TypeScript for any reason (as I said in #24)

Adopting TypeScript was just an example, as there are multiple functions. We don't need to adopt it, and continue using equivalent, like JSDoc.

**Comment by trivikr** [comment]
Moving to draft, as this might break GitHub Action which expects json and etag files in root folder.
It can be revisited after action is moved to a new package in https://github.com/RafaelGSS/is-my-node-vulnerable/issues/22

**Comment by trivikr** [comment]
Replaced by a subset in https://github.com/RafaelGSS/is-my-node-vulnerable/pull/29

**Pull request closed without merging**
